services:
  patients-db:
    image: postgres:16-alpine
    container_name: patients-db
    environment:
      POSTGRES_DB: ${POSTGRES_PATIENTS_DB}
      POSTGRES_USER: ${POSTGRES_PATIENTS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PATIENTS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - patients_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_PATIENTS_USER} -d ${POSTGRES_PATIENTS_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # appointments-db and kafka coming soon

volumes:
  patients_data: