services:
  patients-db:
    image: postgres:16-alpine
    container_name: patients-db
    environment:
      POSTGRES_DB: ${POSTGRES_PATIENTS_DB}
      POSTGRES_USER: ${POSTGRES_PATIENTS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PATIENTS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - patients_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_PATIENTS_USER} -d ${POSTGRES_PATIENTS_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_PATIENTS_DB: ${POSTGRES_PATIENTS_DB}
      POSTGRES_PATIENTS_USER: ${POSTGRES_PATIENTS_USER}
      POSTGRES_PATIENTS_PASSWORD: ${POSTGRES_PATIENTS_PASSWORD}
    depends_on:
      patients-db:
        condition: service_healthy

  appointments-db:
    image: postgres:16-alpine
    container_name: appointments-db
    environment:
      POSTGRES_DB: ${POSTGRES_APPOINTMENTS_DB}
      POSTGRES_USER: ${POSTGRES_APPOINTMENTS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_APPOINTMENTS_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - appointments_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_APPOINTMENTS_USER} -d ${POSTGRES_APPOINTMENTS_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_APPOINTMENTS_DB: ${POSTGRES_APPOINTMENTS_DB}
      POSTGRES_APPOINTMENTS_USER: ${POSTGRES_APPOINTMENTS_USER}
      POSTGRES_APPOINTMENTS_PASSWORD: ${POSTGRES_APPOINTMENTS_PASSWORD}
    depends_on:
      appointments-db:
        condition: service_healthy
      patient-service:
        condition: service_started

  # kafka coming soon

volumes:
  patients_data:
  appointments_data:
