# Server
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_PATIENTS_DB}
spring.datasource.username=${POSTGRES_PATIENTS_USER}
spring.datasource.password=${POSTGRES_PATIENTS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Application
spring.application.name=patient-service