spring.datasource.url=jdbc:postgresql://appointments-db:5432/${POSTGRES_APPOINTMENTS_DB}
spring.datasource.username=${POSTGRES_APPOINTMENTS_USER}
spring.datasource.password=${POSTGRES_APPOINTMENTS_PASSWORD}
patient.service.url=http://patient-service:8081
spring.kafka.bootstrap-servers=kafka:9092
